# Base nutricional (por 100 g ou 100 ml, como consumido). Fonte: aproximações TACO/USDA.
ING = [
 # nome, categoria, kcal, prot, carb, gord, palavras-chave
 ('arroz branco cozido','carbo',128,2.5,28,0.2,'arroz'),
 ('arroz sírio','carbo',150,4,26,3,'arroz sirio|arroz sírio'),
 ('feijão cozido','leguminosa',76,4.8,13.6,0.5,'feijao|feijão'),
 ('feijoada (feijão com carnes)','leguminosa',150,10,10,7,'feijoada'),
 ('massa cozida','carbo',158,5.8,31,0.9,'massa|macarrao|macarrão|spaghetti|espaguete|fettuccine|penne|linguini|linguine|talharim|nhoque|gnocchi|lasanha|ravioli|capeletti|capelete|tortellini|fusilli|rigatoni'),
 ('massa de pizza assada','carbo',275,8,52,3,'pizza'),
 ('pão de hambúrguer','carbo',270,9,50,4,'pao|pão'),
 ('pão francês','carbo',300,9,58,3,'pao frances|pão francês|pao na chapa|pão na chapa'),
 ('pão sírio','carbo',275,9,56,1,'pao sirio|pão sírio|pita'),
 ('tortilla','carbo',300,8,50,7,'tortilla|taco|burrito|quesadilla'),
 ('batata frita','carbo',312,3.4,41,15,'batata frita|fritas|fries|batatas'),
 ('batata doce','carbo',86,1.6,20,0.1,'batata doce'),
 ('polenta','carbo',85,2,18,0.5,'polenta'),
 ('farofa','carbo',400,4,60,16,'farofa'),
 ('quinoa cozida','carbo',120,4.4,21,1.9,'quinoa'),
 ('grão de bico','leguminosa',164,9,27,2.6,'grao de bico|grão de bico|homus|hummus'),
 ('frango grelhado','proteina',165,31,0,3.6,'frango|galeto|sobrecoxa|chicken|peito'),
 ('frango empanado','proteina',250,19,15,13,'frango empanado|nuggets|frango a passarinho|frango frito|crispy'),
 ('carne bovina grelhada','proteina',250,26,0,16,'carne|bovino|picanha|contra file|contrafile|contrafilé|alcatra|fraldinha|bife|steak|rib eye|ribeye|entrecote|ancho|chorizo|maminha'),
 ('filé mignon','proteina',190,29,0,8,'file mignon|filé mignon|filet mignon|mignon'),
 ('costela bovina','proteina',330,22,0,27,'costela|ribs'),
 ('carne moída','proteina',240,22,0,16,'carne moida|carne moída|bolonhesa|ragu|ragú|kafta|kibe|quibe'),
 ('hambúrguer de carne','proteina',250,20,0,18,'burger|hamburguer|hambúrguer|smash|cheeseburger|whopper|big mac'),
 ('porco assado','proteina',250,27,0,15,'porco|suino|suíno|lombo|pernil|leitao|leitão|pork'),
 ('bacon','proteina',540,37,1,42,'bacon'),
 ('linguiça','proteina',290,15,1,25,'linguica|linguiça|calabresa|toscana|chorizo|salsicha|hot dog|cachorro quente'),
 ('chashu (porco)','proteina',300,20,0,24,'chashu|tyashu|char siu'),
 ('salmão','proteina',208,20,0,13,'salmao|salmão|salmon'),
 ('atum','proteina',130,28,0,1,'atum|tuna'),
 ('peixe branco','proteina',110,23,0,2,'peixe|tilapia|tilápia|linguado|robalo|bacalhau|pescada|fish'),
 ('camarão','proteina',99,24,0,1,'camarao|camarão|shrimp'),
 ('lula e polvo','proteina',92,16,3,1,'lula|polvo'),
 ('ovo','proteina',155,13,1,11,'ovo|omelete|egg'),
 ('tofu','proteina',76,8,2,4.8,'tofu'),
 ('mussarela','laticinio',300,22,2,22,'mussarela|muçarela|mozzarella|queijo'),
 ('parmesão','laticinio',430,38,4,29,'parmesao|parmesão|parmegiana|grana'),
 ('catupiry / cream cheese','laticinio',250,9,3,22,'catupiry|requeijao|requeijão|cream cheese|philadelphia'),
 ('queijo prato / presunto','laticinio',280,22,1,20,'presunto|queijo prato|misto'),
 ('molho de tomate','molho',30,1.3,5,0.5,'molho de tomate|pomodoro|sugo|marinara|napolitana'),
 ('molho branco / creme','molho',150,3,6,13,'molho branco|creme|cream|alfredo|carbonara|4 queijos|quatro queijos'),
 ('maionese e molhos gordos','molho',600,1,4,66,'maionese|aioli|molho especial|molho da casa'),
 ('molho barbecue / shoyu','molho',120,1,25,0.3,'barbecue|bbq|shoyu|teriyaki|agridoce|ketchup'),
 ('guacamole','molho',150,2,8,13,'guacamole|abacate|avocado'),
 ('azeite','gordura',884,0,0,100,'azeite'),
 ('manteiga','gordura',720,0.5,0,81,'manteiga'),
 ('salada verde','vegetal',20,1.5,3,0.2,'salada|alface|rucula|rúcula|folhas|mix de folhas'),
 ('legumes cozidos ou grelhados','vegetal',60,2,8,2,'legumes|brocolis|brócolis|abobrinha|berinjela|cenoura|vegetais|couve-flor|aspargos|cogumelo|shimeji'),
 ('couve refogada','vegetal',90,3,8,6,'couve'),
 ('vinagrete','vegetal',50,1,6,3,'vinagrete'),
 ('tabule','vegetal',90,3,12,4,'tabule|tabbouleh'),
 ('arroz de sushi','carbo',130,2.7,29,0.3,'sushi|nigiri|uramaki|hossomaki|hot roll|temaki|combinado|joy|jow|peças|pecas'),
 ('caldo missô','molho',40,3,5,1,'lamen|lámen|ramen|misso|missô|miso'),
 ('caldo / sopa','molho',45,3,5,1.5,'caldo|sopa|brodo|canja|creme de'),
 ('açaí (polpa adoçada)','doce',110,1,20,3,'acai|açaí|açai'),
 ('granola','carbo',450,10,64,16,'granola'),
 ('banana','fruta',90,1,23,0.3,'banana'),
 ('frutas','fruta',55,0.8,13,0.2,'fruta|morango|manga|abacaxi|mamao|mamão|melancia|uva|laranja|salada de frutas'),
 ('suco natural','bebida',45,0.5,11,0,'suco|juice|limonada'),
 ('refrigerante','bebida',42,0,10.6,0,'refrigerante|coca|coca-cola|guarana|guaraná|pepsi|fanta|sprite|soda|tonica|tônica'),
 ('refrigerante zero','bebida',0,0,0,0,'zero|diet|light|sem acucar|sem açúcar'),
 ('água','bebida',0,0,0,0,'agua|água|water'),
 ('cerveja','bebida',43,0.5,3.6,0,'cerveja|chopp|chope|heineken|brahma|stella|corona|budweiser|skol|ipa|lager|pilsen|beer'),
 ('vinho','bebida',85,0,2.6,0,'vinho|wine|espumante|prosecco'),
 ('destilado / caipirinha','bebida',230,0,12,0,'caipirinha|caipiroska|whisky|whiskey|gin|vodka|rum|cachaca|cachaça|tequila|drink|cocktail|coquetel'),
 ('café e chá','bebida',2,0,0,0,'cafe|café|espresso|expresso|cha|chá'),
 ('café com leite / frappuccino','bebida',110,3,16,4,'cappuccino|latte|frappuccino|mocha|chocolate quente|milkshake'),
 ('sorvete / gelato','doce',210,4,24,11,'sorvete|gelato|ice cream|milk shake'),
 ('bolo / torta doce','doce',350,5,50,15,'bolo|torta|cheesecake|brownie|cookie|cupcake|pudim|mousse|tiramisu|petit gateau|doce|sobremesa|dessert'),
 ('chocolate / brigadeiro','doce',480,5,60,24,'chocolate|brigadeiro|nutella|kit kat|kinder|trufa|bombom'),
 ('croissant / folhado','carbo',400,8,45,21,'croissant|folhado|pao de queijo|pão de queijo|salgado|coxinha|esfiha|esfirra|empada|kibe|quibe|pastel|bolinho'),
 ('doces árabes','doce',420,6,55,20,'baklava|doces arabes|doces árabes|marlabie|mhalab|malabi|atayef|nata|halawa|ninho'),
 ('pipoca / snacks','carbo',500,7,55,28,'pipoca|chips|batata palha|salgadinho|doritos|ruffles'),
 ('amendoim / castanhas','gordura',580,25,18,48,'amendoim|castanha|nozes|amêndoa|amendoa|mix de'),
 ('leite','laticinio',60,3.2,4.8,3.2,'leite'),
 ('whey / suplemento proteico','proteina',380,78,8,5,'whey|proteina isolada|proteína isolada|barra de proteina|barra de proteína|suplemento'),
 ('arroz integral cru (pacote)','carbo',350,7,74,2.5,'arroz integral|arroz 7 graos|arroz sete graos|arroz parboilizado'),
 ('arroz cru (pacote)','carbo',360,7,79,0.5,'arroz (branco|tipo 1|parboilizado|agulhinha|camil|tio joao).*(kg|g)\\b'),
 ('cerveja sem álcool','bebida',20,0.3,4.5,0,'cerveja (sem alcool|zero|0[,.]0)'),
 ('iogurte','laticinio',80,4,10,2.5,'iogurte|yogurt|yakult'),
 ('cereal / aveia','carbo',380,10,68,6,'cereal|aveia|sucrilhos|muesli'),
 ('azeitona / conservas','gordura',140,1,3,14,'azeitona|conserva|picles'),
]
NONFOOD='racao|ração|petisco para|shampoo|condicionador|sabonete|desodorante|papel higienico|papel higiênico|detergente|amaciante|sabao|sabão|absorvente|fralda|lenco|lenço|escova|pasta de dente|creme dental|remedio|remédio|comprimido|capsula|cápsula|xarope|pomada|vitamina (c|d|b|complexo)|polivitaminico|creatina|omega|ômega|dipirona|paracetamol|ibuprofeno|omeprazol|antialergico|antialérgico|repelente|protetor solar|pilha|bateria|carregador|cabo|lampada|lâmpada|vela|isqueiro|talher|copo (descartavel|descartável|plastico|plástico|de papel)|guardanapo|saco de lixo|esponja|alcool (gel|70|etilico|etílico|liquido|líquido)|agua sanitaria|água sanitária|desinfetante|inseticida|terra vegetal|adubo|brinquedo|areia|tapete|coleira|numero de pessoas|número de pessoas|taxa|embalagem|entrega|gorjeta|cartao|cartão|presente|voucher|descartav|kit descart|copo colecion|copo ronaldinho|copo personalizado|caneca|brinde|colecionavel|colecionável|sacola|taxa de|adicional de embalagem'

# Pratos: regex -> composição [(ingrediente, gramas)], observações. Ordem importa: o primeiro que casar vence.
PRATOS = [
 ('feijoada', [('feijoada (feijão com carnes)',450),('arroz branco cozido',200),('farofa',50),('couve refogada',60),('linguiça',60)], 'feijoada completa individual'),
 ('combo|mcoferta|oferta .*(burger|big mac|quarterao|quarterão|mcchicken)|meal|trio', [('hambúrguer de carne',140),('pão de hambúrguer',65),('mussarela',30),('maionese e molhos gordos',15),('batata frita',110),('refrigerante',350)], 'combo lanche + batata + refrigerante'),
 ('cafe da manha|café da manhã|brunch|breakfast|cesta', [('pão francês',150),('croissant / folhado',80),('ovo',100),('queijo prato / presunto',100),('frutas',150),('suco natural',400),('manteiga',20),('bolo / torta doce',120)], 'café da manhã completo'),
 ('empanada', [('croissant / folhado',55),('carne moída',40)], 'uma empanada'),
 ('pastel|pasteis|pastéis', [('croissant / folhado',70),('mussarela',30)], 'um pastel'),
 ('coxinha|bolinha de queijo|croquete|rissole|risole|bolinho de bacalhau', [('croissant / folhado',110)], 'um salgado frito'),
 ('guioza|gyoza|harumaki|rolinho primavera|dumpling', [('massa cozida',22),('carne moída',14)], 'uma unidade'),
 ('sanduiche|sanduíche|sanduba|wrap|beirute|bauru|baguete|panini|toast', [('pão francês',90),('frango grelhado',100),('mussarela',30),('maionese e molhos gordos',15),('salada verde',30)], 'sanduíche'),
 ('tapioca|crepe|panqueca|waffle', [('massa de pizza assada',120),('mussarela',50),('queijo prato / presunto',30)], 'tapioca / crepe recheado'),
 ('strogonoff|estrogonofe', [('frango grelhado',180),('molho branco / creme',150),('arroz branco cozido',180),('batata frita',60)], 'strogonoff com arroz e batata palha'),
 ('escondidinho|baiao|baião|moqueca|bobó|bobo de|vatapa|vatapá|carne de sol|dadinho', [('carne bovina grelhada',180),('arroz branco cozido',150),('farofa',40),('feijão cozido',80),('manteiga',15)], 'prato regional'),
 ('ceviche|tiradito', [('peixe branco',180),('legumes cozidos ou grelhados',60)], 'ceviche'),
 ('sashimi', [('salmão',150)], 'sashimi'),
 ('yakimeshi|chahan|arroz frito', [('arroz branco cozido',300),('ovo',50),('legumes cozidos ou grelhados',60),('azeite',10)], 'arroz frito'),
 ('bolo de rolo|bolo inteiro|bolo de pote|torta inteira|bolo .*(kg|g\b)', [('bolo / torta doce',350)], 'bolo inteiro (peso do nome quando houver)'),
 ('torta (doce|de limao|de limão|holandesa|de morango|de chocolate|alema|alemã)|torta de|cheesecake|fatia de bolo|fatia de torta', [('bolo / torta doce',150)], 'fatia de torta doce'),
 ('agua de coco|água de coco|energetico|energético|isotonico|isotônico|gatorade|red bull', [('suco natural',330)], 'bebida 330 ml'),
 ('vitamina|smoothie|shake', [('suco natural',300),('banana',60),('leite',100)], 'vitamina de frutas'),
 ('porcao|porção|petisco|aperitivo|entrada', [('batata frita',150),('linguiça',80)], 'porção de petisco'),
 ('meia porcao|meia porção|1/2 porcao', [('batata frita',80),('linguiça',40)], 'meia porção'),
 ('pizza .*(brotinho|broto|individual|pequena)|brotinho', [('massa de pizza assada',150),('mussarela',90),('molho de tomate',60)], 'pizza brotinho'),
 ('(fatia|pedaço|pedaco).*pizza|pizza.*(fatia|pedaço|pedaco)', [('massa de pizza assada',60),('mussarela',35),('molho de tomate',20)], 'uma fatia de pizza'),
 ('fatia|pedaço|pedaco', [('bolo / torta doce',150)], 'uma fatia (doce)'),
 ('pizza', [('massa de pizza assada',300),('mussarela',180),('molho de tomate',100),('linguiça',40)], 'pizza grande inteira (8 fatias)'),
 ('big mac|quarterao|quarterão|mcchicken|cheddar mcmelt|whopper|double|duplo|triplo|dupla', [('pão de hambúrguer',70),('hambúrguer de carne',140),('mussarela',30),('maionese e molhos gordos',15),('salada verde',30)], 'hambúrguer duplo'),
 ('burger|hamburguer|hambúrguer|smash|cheese|x-|xis|bacon', [('pão de hambúrguer',60),('hambúrguer de carne',150),('mussarela',30),('maionese e molhos gordos',20),('salada verde',30)], 'hambúrguer simples'),
 ('hot dog|cachorro', [('pão francês',60),('linguiça',80),('maionese e molhos gordos',20),('molho de tomate',30),('pipoca / snacks',10)], 'hot dog'),
 ('nuggets|mcnuggets', [('frango empanado',200)], 'nuggets'),
 ('lamen|lámen|ramen|misso|missô|miso|tonkotsu|shoyu ramen|tyashu|tsukemen', [('massa cozida',250),('caldo missô',400),('chashu (porco)',90),('ovo',50),('legumes cozidos ou grelhados',40)], 'lámen completo'),
 ('poke|bowl', [('arroz branco cozido',200),('salmão',120),('legumes cozidos ou grelhados',100),('molho barbecue / shoyu',20)], 'poke / bowl'),
 ('galeto|frango|sobrecoxa|peito', [('frango grelhado',300),('arroz branco cozido',150),('feijão cozido',100),('salada verde',50)], 'frango com acompanhamentos'),
 ('esfiha|esfirra', [('croissant / folhado',80)], 'uma esfiha'),
 ('kibe|quibe', [('carne moída',60),('croissant / folhado',60)], 'um kibe'),
 ('temaki', [('arroz de sushi',80),('salmão',50),('catupiry / cream cheese',20)], 'temaki'),
 ('sushi|combinado|sashimi|nigiri|uramaki|hossomaki|hot roll|peças|pecas|joy|jow', [('arroz de sushi',300),('salmão',150),('catupiry / cream cheese',30)], 'combinado de sushi (~20 a 30 peças)'),
 ('yakisoba', [('massa cozida',250),('legumes cozidos ou grelhados',150),('frango grelhado',100),('molho barbecue / shoyu',30)], 'yakisoba'),
 ('parmegiana', [('carne bovina grelhada',200),('molho de tomate',100),('mussarela',80),('arroz branco cozido',150),('batata frita',120)], 'parmegiana com arroz e fritas'),
 ('mignon|filet|file|filé', [('filé mignon',200),('arroz branco cozido',150),('legumes cozidos ou grelhados',80)], 'filé com acompanhamentos'),
 ('picanha|costela|ribs|prime|rib eye|ribeye|ancho|chorizo|churrasco|rodizio|rodízio', [('carne bovina grelhada',300),('arroz branco cozido',150),('farofa',50),('vinagrete',60)], 'churrasco com acompanhamentos'),
 ('espeto|espetinho', [('carne bovina grelhada',90)], 'um espeto'),
 ('kafta|shawarma|kebab|beirute', [('carne moída',180),('arroz sírio',200),('salada verde',60),('grão de bico',60)], 'prato árabe'),
 ('molcajete|taco|burrito|fajita|nacho|mexican', [('tortilla',120),('carne bovina grelhada',150),('mussarela',40),('guacamole',80),('feijão cozido',100)], 'prato mexicano'),
 ('lasanha', [('massa cozida',200),('carne moída',120),('molho branco / creme',120),('mussarela',60)], 'lasanha'),
 ('risoto|risotto', [('arroz branco cozido',280),('parmesão',40),('manteiga',20),('legumes cozidos ou grelhados',60)], 'risoto'),
 ('nhoque|gnocchi|massa|spaghetti|espaguete|fettuccine|penne|linguini|linguine|talharim|ravioli|capeletti|capelete|tortellini|fusilli|rigatoni|carbonara|bolonhesa', [('massa cozida',250),('molho de tomate',120),('parmesão',30)], 'massa com molho'),
 ('brodo|caldo|sopa|canja|creme de', [('caldo / sopa',400),('massa cozida',80)], 'sopa'),
 ('polenta', [('polenta',300),('linguiça',100),('molho de tomate',80)], 'polenta com ragu'),
 ('camarao|camarão|shrimp', [('camarão',250),('arroz branco cozido',180),('molho branco / creme',100),('mussarela',30)], 'prato de camarão'),
 ('peixe|salmao|salmão|tilapia|tilápia|robalo|bacalhau|moqueca', [('peixe branco',200),('arroz branco cozido',150),('legumes cozidos ou grelhados',100),('azeite',10)], 'peixe com acompanhamentos'),
 ('salada|caesar', [('salada verde',150),('frango grelhado',120),('parmesão',20),('maionese e molhos gordos',20)], 'salada com proteína'),
 ('marmita|prato feito|executivo|pf|refeição|refeicao', [('arroz branco cozido',200),('feijão cozido',150),('carne bovina grelhada',150),('salada verde',60)], 'prato feito'),
 ('suco|juice|limonada', [('suco natural',400)], 'suco 400 ml'),
 ('acai|açaí|açai', [('açaí (polpa adoçada)',400),('granola',40),('banana',60)], 'açaí 500 ml com complementos'),
 ('zero|diet|light', [('refrigerante zero',350)], 'refrigerante zero'),
 ('refrigerante|coca|guarana|guaraná|pepsi|fanta|sprite|soda|bebida', [('refrigerante',350)], 'lata 350 ml'),
 ('cerveja|chopp|chope|heineken|brahma|stella|corona|budweiser|skol|ipa|lager|pilsen', [('cerveja',350)], 'cerveja 350 ml'),
 ('caipirinha|caipiroska|drink|cocktail|coquetel|gin|whisky|vodka', [('destilado / caipirinha',250)], 'drink 250 ml'),
 ('vinho|espumante|prosecco', [('vinho',150)], 'taça de vinho'),
 ('agua|água', [('água',500)], 'água'),
 ('frappuccino|milkshake|milk shake|mocha|latte|cappuccino|chocolate quente', [('café com leite / frappuccino',400)], 'bebida láctea 400 ml'),
 ('cafe|café|espresso|cha |chá', [('café e chá',150)], 'café ou chá'),
 ('pao na chapa|pão na chapa|pao com manteiga|pão com manteiga', [('pão francês',60),('manteiga',15)], 'pão na chapa'),
 ('misto|pão de queijo|pao de queijo|croissant|coxinha|pastel|empada|bolinho|salgado', [('croissant / folhado',90)], 'salgado / folhado'),
 ('gelato|sorvete|ice cream', [('sorvete / gelato',300)], 'sorvete ~300 g'),
 ('bolo', [('bolo / torta doce',320)], 'bolo pequeno inteiro'),
 ('torta|cheesecake|brownie|cookie|pudim|mousse|tiramisu|petit gateau|sobremesa|dessert|doce', [('bolo / torta doce',150)], 'fatia de doce'),
 ('brigadeiro|chocolate|bombom|trufa', [('chocolate / brigadeiro',40)], 'doce pequeno'),
 ('baklava|mhalab|malabi|atayef|nata|halawa|doces arabes|doces árabes', [('doces árabes',120)], 'doce árabe'),
 ('omelete|ovo', [('ovo',120),('mussarela',30)], 'omelete'),
 ('legumes|vegetais|grelhado', [('legumes cozidos ou grelhados',200)], 'legumes'),
 ('batata|fritas|mcfritas|fries', [('batata frita',150)], 'porção de fritas'),
 ('arroz', [('arroz branco cozido',200)], 'porção de arroz'),
 ('feijao|feijão', [('feijão cozido',150)], 'porção de feijão'),
 ('farofa', [('farofa',60)], 'farofa'),
 ('couve', [('couve refogada',80)], 'couve'),
 ('vinagrete', [('vinagrete',80)], 'vinagrete'),
 ('carne|bovino|alcatra|fraldinha|bife|steak|maminha', [('carne bovina grelhada',200),('arroz branco cozido',150),('farofa',40)], 'carne com acompanhamentos'),
 ('porco|lombo|pernil|leitao|leitão|pork', [('porco assado',200),('arroz branco cozido',150),('farofa',40)], 'porco com acompanhamentos'),
 ('linguica|linguiça|calabresa|toscana', [('linguiça',150)], 'linguiça'),
]
