const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const sample=()=>({id:'1234567890123',lastStatus:'CONCLUDED',createdAt:'2026-09-10T12:00:00-03:00',customer:{email:'private@example.test'},merchant:{name:'Loja',type:'RESTAURANT'},delivery:{address:{street:'Segredo'},driver:{name:'Pessoa'}},verificationCodes:[{value:'1234'}],payments:{total:{value:2000}},bag:{subTotal:{value:2000},deliveryFee:{value:0},items:[{name:'Prato 100g',description:'Frango com arroz',quantity:1,totalPrice:2000,notes:'Entregar na casa secreta',weight:{value:100,unit:'g'},subItems:[]}]}});
function harness(platform,responses=[]){
 const calls=[],buttons=[],downloads=[];
 const el=tag=>({style:{},children:[],textContent:'',append(...xs){this.children.push(...xs)},setAttribute(){},remove(){},click(){if(tag==='a')downloads.push(this.download);else this.onclick?.()},...tag==='input'?{files:[]}:{} });
 class XHR{open(m,u){this.url=u;this.method=m}setRequestHeader(){}getResponseHeader(){return null}send(){const next=responses.shift();calls.push(this.url);if(!next)throw Error('Unexpected request '+this.url);this.status=next.status??200;this.responseText=typeof next.body==='string'?next.body:JSON.stringify(next.body);queueMicrotask(()=>this.onload?.())}abort(){this.onabort?.()}}
 const c={window:{fetch:async()=>{}},XMLHttpRequest:XHR,location:{hostname:platform==='ifood'?'www.ifood.com.br':'www.rappi.com.br',origin:platform==='ifood'?'https://www.ifood.com.br':'https://www.rappi.com.br',href:'https://www.'+platform+'.com.br/'},document:{body:el('body'),createElement:tag=>{const e=el(tag);if(tag==='button')buttons.push(e);return e}},alert(){},confirm:()=>true,Headers,URL,Blob,TextEncoder,crypto:crypto.webcrypto,atob,AbortController,queueMicrotask,setTimeout:(f,ms)=>ms>=25000?0:setTimeout(f,0),clearTimeout};
 vm.createContext(c);let source=fs.readFileSync('site/exportadores/'+platform+'.js','utf8');source=source.replace('document.body.append(panel);','window.TEST={ifoodOrder,rappiOrder,capture,collect,manifest,getState:()=>state};document.body.append(panel);');vm.runInContext(source,c);
 return {api:c.window.TEST,c,calls,buttons,downloads,capture:()=>c.window.TEST.capture(platform==='ifood'?'https://www.ifood.com.br/site-api/v4/customers/me/orders':'https://v2.rappi.com.br/api/orders/history-user',{'authorization':'Bearer '+['x',Buffer.from(JSON.stringify({sub:'test-account'})).toString('base64url'),'z'].join('.')})};
}
test('iFood full export preserves identifiers and product fields but omits private blocks',async()=>{const h=harness('ifood',[{body:[sample()]},{body:[]}]);await h.capture();await h.api.collect();const state=h.api.getState(),o=state.orders[0];assert.equal(o.ref,'1234567890123');assert.equal(o.items[0].weight.value,100);assert.equal(o.items[0].qty,1);assert.equal(h.api.manifest().complete,true);const serialized=JSON.stringify(state);assert.ok(!/Segredo|Pessoa|private@|notes|verificationCodes|authorization/.test(serialized));assert.equal(h.calls.length,2)});
test('401 is failure, never end of history; partial result survives',async()=>{const h=harness('ifood',[{body:[sample()]},{status:401,body:{error:'expired'}}]);await h.capture();await h.api.collect();assert.equal(h.api.getState().orders.length,1);assert.equal(h.api.getState().listingDone,false);assert.equal(h.api.manifest().complete,false);assert.match(h.api.getState().errors[0].message,/Sessão/)});
test('invalid JSON and repeated pages cannot declare completeness',async()=>{for(const response of [{body:'<html>Error</html>'},{body:[sample()]}]){const h=harness('ifood',[{body:[sample()]},response]);await h.capture();await h.api.collect();assert.equal(h.api.manifest().complete,false)}});
test('429 retries and successful continuation completes',async()=>{const h=harness('ifood',[{status:429,body:{}},{body:[sample()]},{body:[]}]);await h.capture();await h.api.collect();assert.equal(h.calls.length,3);assert.equal(h.api.manifest().complete,true)});
const list={id:42,status:'finished',created_at:'2026-09-10T12:00:00-03:00',calculated_store_type:'restaurant',store_brand:'Loja'};
const detail=()=>({order_id:42,state:'finished',created_at:list.created_at,store:{name:'Loja',address:'privado'},products:[{name:'Frango',description:'Grelhado',units:2,total_price:20,unit_price:10,presentation:'100 Gramas',toppings:['Sem queijo'],comments:'Casa privada'}],totals:[{description:'Total',value:20},{description:'Custo dos produtos',value:20}],address:{lat:1},cc_data:{last_four_digits:'1234'}});
test('Rappi complete path includes receipt fields without personal data',async()=>{const h=harness('rappi',[{body:{recent_orders:[list],total_recent_orders:1}},{body:{recent_orders:[],total_recent_orders:1}},{body:{data:[]}},{body:detail()}]);await h.capture();await h.api.collect();assert.equal(h.api.manifest().complete,true);const o=h.api.getState().orders[0];assert.equal(o.items[0].pres,'100 Gramas');assert.equal(o.items[0].options[0],'Sem queijo');assert.equal(o.total,20);assert.ok(!JSON.stringify(o).includes('privad'))});
test('Rappi mismatched receipt stops and missing receipt never becomes zero macros',async()=>{const d=detail();d.order_id=99;const h=harness('rappi',[{body:{recent_orders:[list]}},{body:{recent_orders:[]}},{body:{data:[]}},{body:d}]);await h.capture();await h.api.collect();assert.equal(h.api.getState().orders.length,0);assert.equal(h.api.manifest().complete,false)});
test('platform-reported count mismatch flags partial',async()=>{const h=harness('rappi',[{body:{recent_orders:[list],total_recent_orders:2}},{body:{recent_orders:[],total_recent_orders:2}},{body:{data:[]}},{body:detail()}]);await h.capture();await h.api.collect();assert.equal(h.api.manifest().complete,false)});
test('different account pauses instead of merging data',async()=>{const h=harness('ifood');await h.capture();await h.api.capture('https://www.ifood.com.br/site-api/v4/customers/me/orders',{'authorization':'Bearer x.'+Buffer.from(JSON.stringify({sub:'another-account'})).toString('base64url')+'.z'});assert.equal(h.calls.length,0);assert.equal(h.api.getState().orders.length,0)});
function engine(){const c={window:{},setTimeout};vm.createContext(c);vm.runInContext(fs.readFileSync('site/login/engine.js','utf8'),c);return c.window.EatIQEngine}
test('new export imports, checkpoint and incomplete completed rows are rejected',()=>{const h=harness('ifood'),o=h.api.ifoodOrder(sample()),j={schema:'eatiq-export',version:2,platform:'ifood',manifest:{processed:1,complete:true},orders:[o]};const e=engine();assert.equal(e.parseExport(j)[0].items[0].weight.value,100);assert.throws(()=>e.parseExport({...j,checkpoint:true}),/retomada/);assert.throws(()=>e.parseExport({...j,orders:[{...o,total:null}]}),/total/);assert.throws(()=>e.parseExport({...j,orders:[{...o,items:[]}]}),/incompleto/)});
test('generated scripts parse and HTML embeds exactly their code',()=>{for(const platform of ['ifood','rappi']){const script=fs.readFileSync('site/exportadores/'+platform+'.js','utf8');new vm.Script(script);const html=fs.readFileSync('site/exportar-'+platform+'.html','utf8');const textarea=html.match(/<textarea[^>]*>([\s\S]*?)<\/textarea>/)[1].replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#x27;/g,"'").replace(/&amp;/g,'&');assert.equal(textarea,script);assert.ok(!html.includes('eatiq-landing.html'))}});
test('resume continues failed page without duplicating prior orders',async()=>{const responses=[{body:[sample()]},{status:401,body:{}}];const h=harness('ifood',responses);await h.capture();await h.api.collect();assert.equal(h.api.getState().page,1);responses.push({body:[]});await h.capture();await h.api.collect();assert.equal(h.api.manifest().complete,true);assert.equal(h.api.getState().orders.length,1);assert.match(h.calls.at(-1),/page=1/)});
test('missing price rejects a completed page instead of silently inventing zero',async()=>{const o=sample();delete o.bag.items[0].totalPrice;const h=harness('ifood',[{body:[o]}]);await h.capture();await h.api.collect();assert.equal(h.api.getState().page,0);assert.equal(h.api.getState().orders.length,0);assert.equal(h.api.manifest().complete,false)});
test('new export runs through atomic import with weights and options',async()=>{const h=harness('rappi'),o=h.api.rappiOrder(detail(),list),j={schema:'eatiq-export',version:2,platform:'rappi',manifest:{processed:1,complete:true},orders:[o]};const e=engine(),batches=[];
 const ingredients=[{nome:'frango grelhado',categoria:'proteina',palavras:'frango',kcal:165,prot:31,carb:0,gord:3.6}];
 const api=async(path,opts)=>{let data=[];if(path.includes('nutri_ingredientes'))data=ingredients;else if(path.includes('importar_pedidos_v2')){const payload=JSON.parse(opts.body);batches.push(payload);data={gravados:1}}else if(path.includes('recalcular'))data=1;return {ok:true,json:async()=>data}};
 await e.run({name:'rappi_eatiq.json',size:1000,text:async()=>JSON.stringify(j)},{api,userId:'test'});assert.equal(batches.length,1);const item=batches[0].p_pedidos[0].itens_detalhe[0];assert.equal(item.gramas,200);assert.equal(item.kcal,330);assert.equal(item.prot,62);
});
test('panel guides waiting, collection and download while keeping recovery available',async()=>{
 const h=harness('ifood',[{body:[sample()]},{body:[]}]);
 const start=h.buttons[0],pause=h.buttons[1],save=h.buttons[2];
 assert.equal(start.disabled,true);assert.equal(pause.hidden,true);assert.equal(save.hidden,true);
 await h.capture();assert.equal(start.disabled,false);
 const pending=h.api.collect();assert.equal(start.hidden,true);assert.equal(pause.hidden,false);assert.equal(save.hidden,true);
 await pending;assert.equal(start.hidden,true);assert.equal(pause.hidden,true);assert.equal(save.hidden,false);
 save.click();assert.match(h.downloads[0],/^ifood_eatiq_.*\.json$/);
 const panel=h.c.document.body.children[0],link=panel.children.find(e=>e.href?.includes('/login/'));
 assert.equal(link.hidden,false);assert.equal(link.rel,'noopener noreferrer');
});
test('interrupted collection exposes partial download and waits for renewed session',async()=>{
 const h=harness('ifood',[{body:[sample()]},{status:401,body:{}}]);await h.capture();await h.api.collect();
 assert.equal(h.buttons[0].hidden,false);assert.equal(h.buttons[0].disabled,true);
 assert.equal(h.buttons[2].hidden,false);assert.match(h.buttons[2].textContent,/parcial/);
});
