const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const c={window:{}};vm.createContext(c);vm.runInContext(fs.readFileSync('site/login/finance.js','utf8'),c);const f=c.window.EatIQFinance;
const o=(m,tot,extra={})=>({meal:true,m,tot,sub:tot,fee:0,tip:0,disc:0,p:'iFood',s:'A',dow:1,...extra});
test('monthly mean includes internal empty months and median is not average',()=>{const a=f.analyze([o('2026-01',20),o('2026-03',30),o('2026-03',100)]);assert.equal(a.months.length,3);assert.equal(a.monthlyAverage,50);assert.equal(a.median,30);assert.equal(a.months[1].food,0)});
test('total paid is authoritative and discrepancy remains visible',()=>{const a=f.analyze([o('2026-01',90,{sub:100,fee:10,tip:5,disc:20})]);assert.equal(a.total,90);assert.equal(a.expected,95);assert.equal(a.residual,-5)});
test('blank comparison inputs do not invent market prices; explicit zero works',()=>{const p={people:1,ingredients:'',energy:'',dish:'',service:'',transport:''};assert.equal(f.scenario([o('2026-01',80)],p).home,null);const a=f.scenario([o('2026-01',80)],{people:2,ingredients:15,energy:0,dish:30,service:10,transport:0});assert.equal(a.home,30);assert.equal(a.out,66);assert.equal(a.outDifference,-14)});
test('same restaurant on different platforms counts separately and nonfood excluded',()=>{const a=f.analyze([o('2026-01',10),o('2026-01',20,{p:'Rappi'}),o('2026-01',1000,{meal:false})]);assert.equal(a.n,2);assert.equal(a.allTotal,1030);assert.equal(a.apps.length,2);assert.equal(a.total,30)});
test('rejects invalid portion count and does not extrapolate empty histories',()=>{assert.equal(f.scenario([],{people:1}),null);assert.equal(f.scenario([o('2026-01',80)],{people:0}),null);assert.equal(f.analyze([]).monthlyAverage,0)});
test('batch cooking rounds preparations up and accounts for loss and optional time',()=>{
 const a=f.scenario(Array.from({length:5},()=>o('2026-01',80)),{people:2,ingredients:10,energy:4,batch:2,waste:20,minutes:30,hour:20,dish:30,service:10,transport:8});
 assert.equal(a.batches,3);assert.equal(a.ingredientsCost,125);assert.equal(a.energyCost,12);assert.equal(a.timeCost,30);assert.equal(a.home,167);assert.equal(a.out,370);assert.equal(a.portions,10);assert.ok(Math.abs(a.breakEvenIngredients-28.64)<1e-10);
});
test('invalid yield or complete loss invalidates home only; restaurant remains usable',()=>{
 const p={people:1,ingredients:10,energy:2,dish:30,service:0,transport:0};
 for(const extra of [{waste:100},{batch:0},{batch:1.5},{hour:-1}]){const a=f.scenario([o('2026-01',80)],{...p,...extra});assert.equal(a.home,null);assert.equal(a.out,30);}
});
test('invalid people cannot silently show a one-person delivery comparison',()=>{assert.equal(f.scenario([o('2026-01',80)],{people:''}),null);});
test('financial UI reacts to assumptions and keeps negative differences',()=>{const els=new Map();const ctx={window:{},document:{getElementById(id){if(!els.has(id))els.set(id,{value:({'finance-people':'1','finance-batch':'1','finance-waste':'0','finance-minutes':'30','finance-hour':'0'}[id]??''),innerHTML:'',textContent:''});return els.get(id)}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('site/login/finance.js','utf8'),ctx);ctx.window.EatIQFinance.render([o('2026-01',80,{date:new Date('2026-01-05T12:00:00')})]);assert.equal(els.get('extraMarket').textContent,'—');els.get('finance-ingredients').value='100';els.get('finance-energy').value='0';els.get('finance-energy').oninput();assert.match(els.get('extraMarket').textContent,/-/);assert.match(els.get('cookSave').textContent,/-/);assert.ok(!els.get('cookFoot').textContent.includes('kcal'))});
