const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
process.env.TZ='America/Sao_Paulo';
function setup(){const nodes=new Map();const c={window:{},document:{getElementById(id){if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'all',dataset:{},addEventListener(_,fn){this.change=fn}});return nodes.get(id)}}};vm.createContext(c);vm.runInContext(fs.readFileSync('site/login/habit-insights.js','utf8'),c);return {...c.window.EatIQHabits,nodes};}
let id=0;function row(day=0,extra={}){return {id:++id,tipo:'Restaurante',app:'iFood',loja:'A',criado_em:new Date(2026,0,5+day,19).toISOString(),total:50,produtos:45,taxas:5,gorjeta:0,desconto:0,kcal:500,prot:25,confianca:45,...extra};}
const card=(rows,key)=>setup().analyze(rows).cards.find(c=>c.id===key);
test('exactly ten cards persist with honest empty states and no invalid numbers',()=>{const a=setup();a.render([]);assert.equal(a.analyze([]).cards.length,10);assert.equal(a.analyze([]).ready,0);assert.equal((a.nodes.get('habitCards').innerHTML.match(/data-habit=/g)||[]).length,10);assert.ok(!/NaN|Infinity/.test(a.nodes.get('habitCards').innerHTML));});
test('repetition counts transitions, not popularity, and keeps platforms separate',()=>{const rs=['A','A','B','B','A','A','B','B','A','A'].map((loja,i)=>row(i,{loja}));const c=card(rs,'repeat');assert.equal(c.ready,true);assert.equal(c.bars[0].value,5);assert.equal(c.bars[1].value,4);const copy=[...rs,rs[0]];assert.equal(card(copy,'repeat').bars[0].value,5);});
test('discovery return uses only mature cohorts and excludes same-day repeats',()=>{const rs=[row(0),row(80)];for(let i=0;i<5;i++){rs.push(row(14+i,{loja:'New'+i}));rs.push(row(14+i,{loja:'New'+i}));if(i<3)rs.push(row(24+i,{loja:'New'+i}));}rs.push(row(65,{loja:'Too recent'}));const c=card(rs,'discovery');assert.equal(c.value,'3 de 5');});
test('day-after rates use all calendar opportunities and count multiple orders once',()=>{const rs=Array.from({length:21},(_,i)=>row(i*3));const c=card(rs,'momentum');assert.equal(c.bars[0].value,0);assert.equal(c.bars[1].value,50);assert.match(c.value,/50/);assert.equal(card([...rs,row(3)],'momentum').value,c.value);});
test('weekend normalizes by two versus five days and excludes incomplete edges',()=>{const rs=Array.from({length:28},(_,i)=>row(i,{total:i%7>=5?20:10}));const c=card(rs,'weekend');assert.equal(c.bars[0].value,20);assert.equal(c.bars[1].value,10);assert.equal(card([...rs,row(28,{total:10000})],'weekend').bars[1].value,10);});
test('late-night comparison excludes lunch and weak nutrition estimates',()=>{const rs=[];for(let i=0;i<5;i++){rs.push(row(i));rs.push(row(i,{criado_em:new Date(2026,0,5+i,23).toISOString(),kcal:750}));}rs.push(row(0,{criado_em:new Date(2026,0,5,13).toISOString(),kcal:9000}));rs.push(row(0,{criado_em:new Date(2026,0,5,23).toISOString(),kcal:9000,confianca:15}));const c=card(rs,'late');assert.equal(c.value,'+50%');assert.equal(c.bars[0].value,500);assert.equal(c.bars[1].value,750);});
test('discount comparison chooses the most sampled shared store, not largest effect',()=>{const rs=[];for(let i=0;i<4;i++){rs.push(row(i,{total:60,desconto:10}));rs.push(row(i,{total:50}));}for(let i=0;i<3;i++){rs.push(row(i,{loja:'B',total:5,desconto:10}));rs.push(row(i,{loja:'B',total:100}));}const c=card(rs,'discount');assert.match(c.summary,/A · iFood/);assert.equal(c.bars[0].value,60);assert.equal(c.bars[1].value,50);assert.equal(card(rs.map(r=>({...r,desconto:null})),'discount').ready,false);});
test('fee shares use ratios of sums and never invent absent charges',()=>{const rs=[...Array.from({length:5},(_,i)=>row(i,{produtos:10,total:20,taxas:10})),...Array.from({length:5},(_,i)=>row(i,{produtos:100,total:110,taxas:10}))];const c=card(rs,'fees');assert.equal(c.bars[0].value,50);assert.ok(Math.abs(c.bars[1].value-100/11)<1e-10);assert.equal(card(rs.map(r=>({...r,taxas:null})),'fees').ready,false);});
test('top fifth uses ceiling for count and reconciles all spend',()=>{const rs=[row(0,{total:90}),...Array.from({length:9},(_,i)=>row(i,{total:10}))];const c=card(rs,'spikes');assert.equal(c.bars[0].value,100);assert.equal(c.bars[1].value,80);assert.match(c.value,/55,6/);});
test('protein comparison normalizes energy and rejects tied price bands',()=>{const rs=Array.from({length:20},(_,i)=>row(i,{total:i+1,prot:i<10?20:40}));const c=card(rs,'protein');assert.equal(c.bars[0].value,40);assert.equal(c.bars[1].value,80);assert.equal(c.value,'+40 g');assert.equal(card(rs.map(r=>({...r,total:20})),'protein').ready,false);});
test('two-hour rhythm window crosses midnight and requires enough history',()=>{const rs=Array.from({length:25},(_,i)=>row(i,{criado_em:new Date(2026,0,5+i,i<10?23:i<20?0:12).toISOString()}));const c=card(rs,'clock');assert.equal(c.value,'23h–1h');assert.equal(c.bars[0].value,20);assert.equal(card(rs.slice(0,10),'clock').ready,false);});
test('category filter works and untrusted restaurant names remain text',()=>{const a=setup(),rs=Array.from({length:10},(_,i)=>row(i,{loja:'<img onerror=alert(1)>',desconto:i<5?10:0}));a.render(rs);assert.ok(!a.nodes.get('habitCards').innerHTML.includes('<img'));const select=a.nodes.get('habitCategory');select.value='bolso';select.change();assert.equal((a.nodes.get('habitCards').innerHTML.match(/data-habit=/g)||[]).length,3);a.render([]);assert.match(a.nodes.get('habitStatus').textContent,/0 de 10/);});
test('nonrestaurant records and invalid dates cannot enter behavioral analysis',()=>{const a=setup().analyze([row(0,{tipo:'Mercado'}),row(0,{criado_em:'invalid'}),row(0,{criado_em:null})]);assert.equal(a.count,0);});
