const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup(){const els=new Map();for(const id of ['descobertas','recommendationGoal','retryInsights','dishPopularity','restaurantPopularity','dishSuggestions','restaurantSuggestions','insightsStatus'])els.set(id,{dataset:{},value:'economia',innerHTML:'',textContent:'',addEventListener(){}});const c={window:{},document:{getElementById:id=>els.get(id)}};vm.createContext(c);vm.runInContext(fs.readFileSync('site/login/insights.js','utf8'),c);return {e:c.window.EatIQInsights,els}}
const order=(id,store='A',app='iFood')=>({id,loja:store,app,tipo:'Restaurante',total:60,criado_em:'2026-09-10T12:00:00Z'});
const item=(id,pedido_id,extra={})=>({id,pedido_id,nome:'Prato de frango',quantidade:1,preco:30,alimento:true,gramas:300,kcal:500,prot:30,carb:60,gord:15,confianca:55,prato:'receita estimada',...extra});
test('frequency counts distinct orders; averages are weighted by units',()=>{const {e}=setup();const r=e.aggregate([order(1),order(2)],[item(1,1,{quantidade:2,preco:60,gramas:600,kcal:1000,prot:60,carb:120,gord:30}),item(2,1),item(3,2)]);assert.equal(r.popular[0].count,2);assert.equal(r.popular[0].units,4);assert.equal(r.popular[0].price,30);assert.equal(r.popular[0].k,500);assert.equal(r.restaurants[0].count,2)});
test('platforms and restaurants stay separate; unselected orders are excluded',()=>{const {e}=setup();const r=e.aggregate([order(1),order(2,'A','Rappi'),order(3,'B')],[item(1,1),item(2,2),item(3,3),item(4,99)]);assert.equal(r.popular.length,3);assert.equal(r.restaurants.length,3);assert.equal(r.orderCount,3)});
test('missing nutrition and low-confidence or extra items cannot be recommended',()=>{const {e}=setup();const r=e.aggregate([order(1)],[item(1,1,{nome:'A',prot:null}),item(2,1,{nome:'B',confianca:20}),item(3,1,{nome:'C',prato:'complemento: frango'}),item(4,1,{nome:'Água',kcal:0})]);assert.equal(r.suggestions.length,0);assert.equal(r.popular.length,4)});
test('objective changes ordering and restaurant picks follow it',()=>{const {e}=setup();const os=[order(1,'A'),order(2,'B')],is=[item(1,1,{preco:20,prot:10}),item(2,2,{preco:40,prot:60})];assert.equal(e.aggregate(os,is,'economia').suggestions[0].store,'A');assert.equal(e.aggregate(os,is,'proteina').suggestions[0].store,'B');assert.equal(e.aggregate(os,is,'proteina').recommendedStores[0].name,'B')});
test('HTML escapes untrusted dish and restaurant names',async()=>{const {e,els}=setup();await e.render({userId:'u',orders:[order(1,'<img src=x>')],api:async()=>({ok:true,json:async()=>[item(1,1,{nome:'<script>alert(1)</script>'})]})});assert.ok(!els.get('dishPopularity').innerHTML.includes('<script>'));assert.ok(els.get('dishPopularity').innerHTML.includes('&lt;script&gt;'))});
test('pagination passes 1000 items and scoping includes user id',async()=>{const {e}=setup();let calls=0;await e.render({userId:'user',orders:[order(1)],api:async path=>{calls++;assert.match(path,/user_id=eq.user/);return {ok:true,json:async()=>path.includes('offset=0')?Array.from({length:1000},(_,i)=>item(i,1)):[]}}});assert.equal(calls,2)});
test('failed loads show error rather than empty ranking and can retry',async()=>{const {e,els}=setup();await e.render({userId:'u',orders:[order(1)],api:async()=>({ok:false})});assert.equal(els.get('retryInsights').hidden,false);assert.match(els.get('dishPopularity').textContent,/Não foi possível/)});
test('late response cannot overwrite a newer filter',async()=>{const {e,els}=setup();let resolve;const old=e.render({userId:'u',orders:[order(1)],api:()=>new Promise(r=>resolve=r)});await e.render({userId:'u',orders:[],api:async()=>({ok:true,json:async()=>[]})});resolve({ok:true,json:async()=>[item(1,1)]});await old;assert.match(els.get('insightsStatus').textContent,/^0 pedidos/)});
