const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup(){const els=new Map();for(const id of ['descobertas','recommendationGoal','retryInsights','dishPopularity','restaurantPopularity','dishSuggestions','restaurantSuggestions','insightsStatus'])els.set(id,{dataset:{},value:'descobrir',innerHTML:'',textContent:'',addEventListener(){}});const c={window:{},document:{getElementById:id=>els.get(id)}};vm.createContext(c);vm.runInContext(fs.readFileSync('site/login/taste.js','utf8'),c);vm.runInContext(fs.readFileSync('site/login/insights.js','utf8'),c);return {e:c.window.EatIQInsights,els}}
const order=(id,store='A',app='iFood')=>({id,loja:store,app,tipo:'Restaurante',total:60,criado_em:'2026-09-10T12:00:00Z'});
const item=(id,pedido_id,extra={})=>({id,pedido_id,nome:'Prato de frango',quantidade:1,preco:30,alimento:true,gramas:300,kcal:500,prot:30,carb:60,gord:15,confianca:55,prato:'receita estimada',...extra});
test('frequency counts distinct orders; averages are weighted by units',()=>{const {e}=setup();const r=e.aggregate([order(1),order(2)],[item(1,1,{quantidade:2,preco:60,gramas:600,kcal:1000,prot:60,carb:120,gord:30}),item(2,1),item(3,2)]);assert.equal(r.popular[0].count,2);assert.equal(r.popular[0].units,4);assert.equal(r.popular[0].price,30);assert.equal(r.popular[0].k,500);assert.equal(r.restaurants[0].count,2)});
test('platforms and restaurants stay separate; unselected orders are excluded',()=>{const {e}=setup();const r=e.aggregate([order(1),order(2,'A','Rappi'),order(3,'B')],[item(1,1),item(2,2),item(3,3),item(4,99)]);assert.equal(r.popular.length,3);assert.equal(r.restaurants.length,3);assert.equal(r.orderCount,3)});
test('HTML escapes untrusted dish and restaurant names',async()=>{const {e,els}=setup();await e.render({userId:'u',orders:[order(1,'<img src=x>')],api:async()=>({ok:true,json:async()=>[item(1,1,{nome:'<script>alert(1)</script>'})]})});assert.ok(!els.get('dishPopularity').innerHTML.includes('<script>'));assert.ok(els.get('dishPopularity').innerHTML.includes('&lt;script&gt;'))});
test('pagination passes 1000 items and scoping includes user id',async()=>{const {e}=setup();let calls=0;await e.render({userId:'user',orders:[order(1)],api:async path=>{if(path.includes('shared_menu'))return {ok:true,json:async()=>[]};calls++;assert.match(path,/user_id=eq.user/);return {ok:true,json:async()=>path.includes('offset=0')?Array.from({length:1000},(_,i)=>item(i,1)):[]}}});assert.equal(calls,2)});
test('failed loads show error rather than empty ranking and can retry',async()=>{const {e,els}=setup();await e.render({userId:'u',orders:[order(1)],api:async()=>({ok:false})});assert.equal(els.get('retryInsights').hidden,false);assert.match(els.get('dishPopularity').textContent,/Não foi possível/)});
test('late response cannot overwrite a newer filter',async()=>{const {e,els}=setup();let resolve;const old=e.render({userId:'u',orders:[order(1)],api:()=>new Promise(r=>resolve=r)});await e.render({userId:'u',orders:[],api:async()=>({ok:true,json:async()=>[]})});resolve({ok:true,json:async()=>[item(1,1)]});await old;assert.match(els.get('insightsStatus').textContent,/^0 pedidos/)});
test('menu renders real ratings and escapes malicious descriptions',async()=>{const {e,els}=setup();const menu={collectedAt:'2026-09-10',stores:[{id:'s',name:'S',rating:4.8,reviews:100,url:'javascript:alert(1)'}],items:[{id:'m',storeId:'s',name:'Pizza nova',description:'<img onerror=alert(1)>',price:50}]};await e.render({userId:'u',orders:[order(1)],api:async p=>({ok:true,json:async()=>p.includes('shared_menu')?[{data:menu}]:[item(1,1,{nome:'Pizza antiga'})]})});const html=els.get('dishSuggestions').innerHTML;assert.match(html,/Pizza nova/);assert.match(html,/100 avaliações/);assert.ok(!html.includes('<img'));assert.ok(!html.includes('javascript:'));assert.ok(!html.includes('kcal'))});
test('menu failure preserves popular rankings and offers retry',async()=>{const {e,els}=setup();await e.render({userId:'u',orders:[order(1)],api:async p=>p.includes('shared_menu')?{ok:false}:{ok:true,json:async()=>[item(1,1,{nome:'Pizza antiga'})]}});assert.match(els.get('dishPopularity').innerHTML,/Pizza antiga/);assert.equal(els.get('retryInsights').hidden,false);assert.match(els.get('dishSuggestions').innerHTML,/consultar os cardápios/)});
