const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const sql=fs.readFileSync('supabase/supabase-motor.sql','utf8');
const ingredients=[...sql.matchAll(/^\('([^']+)','([^']+)',([\d.]+),([\d.]+),([\d.]+),([\d.]+),'([^']+)'\)/gm)].map(m=>({nome:m[1],categoria:m[2],kcal:+m[3],prot:+m[4],carb:+m[5],gord:+m[6],palavras:m[7]}));
const pratos=[...sql.matchAll(/^\((\d+),'([^']+)','([^']+)','([^']+)'::jsonb\)/gm)].map(m=>({ordem:+m[1],padrao:m[2],descricao:m[3],composicao:JSON.parse(m[4])}));
const response=(data,ok=true)=>({ok,status:ok?200:500,json:async()=>data,text:async()=>JSON.stringify(data)});
const base=async(p,scale=1)=>response(p.includes('ingredientes')?ingredients.map(x=>({...x,kcal:x.kcal*scale})):p.includes('pratos')?pratos:[{chave:'nao_alimento',valor:'shampoo|sabao'}]);
async function engine(){const c={window:{},setTimeout};vm.createContext(c);vm.runInContext(fs.readFileSync('site/login/engine.js','utf8'),c);await c.window.EatIQEngine.loadBase(base);return c.window.EatIQEngine}
test('known declared weight overrides grande multiplier',async()=>{const e=await engine();assert.equal(e.estimate('Bolo grande 1kg','',1,'restaurante',{}).gramas,1000)});
test('unmatched component remains in combination estimate',async()=>{const e=await engine();assert.ok(e.estimate('Cerveja 350ml + produto desconhecido','',1,'restaurante',{}).kcal>e.estimate('Cerveja 350ml','',1,'restaurante',{}).kcal)});
test('reloaded ingredient data invalidates cached lookup',async()=>{const e=await engine();const a=e.estimate('arroz','',1,'restaurante',{}).kcal;await e.loadBase(p=>base(p,2));assert.equal(e.estimate('arroz','',1,'restaurante',{}).kcal,2*a)});
test('zero soda and multipack size remain correct',async()=>{const e=await engine();assert.equal(e.estimate('Coca-Cola Zero 350ml','',1,'restaurante',{}).kcal,0);assert.equal(e.estimate('Cerveja 6x350ml','',2,'mercado',{}).gramas,4200)});
const order=i=>({id:String(i),lastStatus:'CONCLUDED',createdAt:'2026-09-01T12:00:00Z',merchant:{name:'Loja',type:'RESTAURANT'},bag:{items:[{name:'arroz',quantity:1,totalPrice:1000}]},payments:{total:{value:1000}}});
const file=orders=>({name:'ifood.json',size:100,text:async()=>JSON.stringify(orders)});
test('deduplication paginates beyond 1000 and refreshes products on retry',async()=>{const e=await engine();let pages=0,recalc=0;await e.run(file([order(1001)]),{userId:'u',api:async(p)=>{if(p.includes('nutri_'))return base(p);if(p.includes('/pedidos?')){pages++;return response(p.includes('offset=0')?Array.from({length:1000},(_,i)=>({pedido_ref:String(i)})):[{pedido_ref:'1001'}])}if(p.includes('recalcular')){recalc++;return response(0)}throw Error('Unexpected '+p)}});assert.equal(pages,2);assert.equal(recalc,1)});
test('reprocess uses atomic upsert without deleting historical orders',async()=>{const e=await engine();let batches=0;const result=await e.run(file([order(1),order(1)]),{userId:'u',reprocess:true,api:async(p,o)=>{if(p.includes('nutri_'))return base(p);if(p.includes('importar_pedidos_v2')){const v=JSON.parse(o.body);assert.equal(v.p_reprocessar,true);assert.equal(v.p_pedidos.length,1);batches++;return response({gravados:1})}if(p.includes('recalcular'))return response(1);throw Error('Unexpected destructive/read request '+p)}});assert.equal(batches,1);assert.equal(result.novos,1)});
test('failed second batch reports saved progress and does not delete',async()=>{const e=await engine();let batches=0;await assert.rejects(e.run(file(Array.from({length:101},(_,i)=>order(i))),{userId:'u',api:async(p,o)=>{if(p.includes('nutri_'))return base(p);if(p.includes('/pedidos?'))return response([]);if(p.includes('importar_pedidos_v2'))return ++batches===1?response({gravados:100}):response({},false);throw Error('Unexpected '+p)}}),/100 pedidos já gravados/);assert.equal(batches,2)});
test('invalid file data rejected before any write',async()=>{const e=await engine();const o=order(1);o.createdAt='bad';await assert.rejects(e.run(file([o]),{userId:'u',api:async p=>{if(p.includes('nutri_'))return base(p);throw Error('Unexpected write')}}),/Nenhum dado foi gravado/)});
function health(extra={}){const c={window:{},TextDecoder,Uint8Array,setTimeout,...extra};vm.createContext(c);vm.runInContext(fs.readFileSync('site/login/health.js','utf8'),c);return c.window.EatIQHealth}
test('Health handles chunk boundaries, pounds, kJ and latest weight',()=>{const p=health().parser();const xml='<Record type="HKQuantityTypeIdentifierBodyMass" unit="lb" value="200" startDate="2026-09-01 10:00:00 -0300"/><Record type="HKQuantityTypeIdentifierActiveEnergyBurned" unit="kJ" value="418.4" startDate="2026-09-01 10:00:00 -0300" sourceName="Watch"/>';for(let i=0;i<xml.length;i+=11)p.feed(xml.slice(i,i+11));p.feed('',true);assert.equal(p.rows()[0].kcal_ativas,100);assert.ok(Math.abs(p.rows()[0].peso-90.718474)<0.001)});
test('Health deduplicates overlapping sleep intervals',()=>{const p=health().parser();for(const [s,e] of [['01','03'],['02','04']])p.feed(`<Record type="HKCategoryTypeIdentifierSleepAnalysis" value="HKCategoryValueSleepAnalysisAsleepCore" startDate="2026-09-01 ${s}:00:00 -0300" endDate="2026-09-01 ${e}:00:00 -0300" sourceName="Watch"/>`);assert.equal(p.rows()[0].sono_min,180)});
test('ZIP without export.xml terminates with a useful error',async()=>{const h=health({fflate:{Unzip:class{register(){}push(){}},UnzipInflate:class{}}});const blob=new Blob(['empty']);await assert.rejects(h.read({name:'empty.zip',stream:()=>blob.stream()}),/ZIP sem export.xml/)});
test('all local script references exist and all JS parses',()=>{const html=fs.readFileSync('site/login/index.html','utf8');for(const m of html.matchAll(/<script src="([^:"]+)"/g)){assert.ok(fs.existsSync('site/login/'+m[1]),m[1]);new vm.Script(fs.readFileSync('site/login/'+m[1],'utf8'))}assert.equal([...html.matchAll(/xlsx.full.min.js/g)].length,1);assert.ok(!html.includes("script-src 'self' 'unsafe-inline'"))});
function app(){
 const html=fs.readFileSync('site/login/index.html','utf8'),els=new Map([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>[m[1],{style:{},dataset:{},value:'',textContent:'',innerHTML:'',disabled:false,addEventListener(){},querySelectorAll(){return []}}]));
 const c={window:{},setTimeout,clearTimeout,URLSearchParams,console,location:{hash:'',pathname:'/login/',origin:'https://test.invalid'},history:{replaceState(){}},localStorage:{getItem(){return null},setItem(){},removeItem(){}},document:{getElementById(id){if(!els.has(id))throw Error('Missing DOM element '+id);return els.get(id)},querySelectorAll(){return []}},fetch:async()=>response([])};vm.createContext(c);vm.runInContext(fs.readFileSync('site/login/analysis-cards.js','utf8'),c);vm.runInContext(fs.readFileSync('site/login/habit-insights.js','utf8'),c);vm.runInContext(fs.readFileSync('site/login/app.js','utf8'),c);return {c,els,run:s=>vm.runInContext(s,c)};
}
test('profile accepts zero premises and calendar uses local day',()=>{process.env.TZ='America/Sao_Paulo';const a=app();assert.equal(a.run("PROF={porcao_grande_pct:0,corte_cenario:0,kcal_fora_delivery:0};profile().cut"),0);assert.equal(a.run('profile().share'),0);assert.equal(a.run('profile().base0'),0);assert.equal(a.run("dayKey(new Date('2026-09-02T01:00:00Z'))"),'2026-09-01')});
test('dashboard render works with empty and populated data; table pages beyond 400',()=>{const a=app();a.run("PROF={peso:80,altura:180,idade:36};render()");a.run("window.__rawO=Array.from({length:450},(_,i)=>({id:i,app:'iFood',criado_em:'2026-09-01T12:00:00Z',loja:'Loja',tipo:'Restaurante',tipo_loja:'RESTAURANT',total:20,produtos:20,kcal:500,prot:20,carb:60,gord:10}));render();tablePage=4;drawTable()");assert.match(a.els.get('tableSub').textContent,/450.*página 5/);assert.equal((a.els.get('tbody').innerHTML.match(/<tr>/g)||[]).length,50)});
